export default {
  'SELECTE_ALBUM': 'SELECTE_ALBUM',
  'SELECTE_SINGER': 'SELECTE_SINGER',
  'SET_PLAYLIST': 'SET_PLAYLIST',
  'SET_PLAYINGSTATE': 'SET_PLAYINGSTATE',
  'SET_PLAYINGMODE': 'SET_PLAYINGMODE',
  'SET_CURRENTINDEX': 'SET_CURRENTINDEX',
  'SET_FULLSCREEN': 'SET_FULLSCREEN',
  'SET_SEQUENCELIST': 'SET_SEQUENCELIST'
}
